// @ts-nocheck
import { useCallback, useEffect, useState } from "react";
import { Autocomplete, Box, Typography, Button, Paper, TextField, Select, MenuItem, FormControl, InputLabel, Stack, CircularProgress, Pagination } from "@mui/material";
import { Add, Download, CalendarTodayOutlined, ScheduleOutlined, PeopleOutlined, DoneAll } from "@mui/icons-material";
import { toast } from "react-hot-toast";
import { useSearchParams } from "react-router-dom";
import { useAuth } from "@/contexts/AuthContext";
import { cancelBanquetBookingApi, createBanquetBookingApi, exportBanquetBookingsApi, getBanquetBookingsApi, updateBanquetStatusApi } from "@/apis/banquet";
import { getUsersApi } from "@/apis/user";
import { getManagerDashboardOverviewApi } from "@/apis/dashboard";

const BRAND="#24528C",GREEN="#22c55e",GOLD="#a17a3f",MUT="#64748b",INK="#1e293b",BG="#f1f5f9",LINE="#e2e8f0",RED="#ef4444";
const STATUSES=["TENTATIVE","CONFIRMED","CANCELLED","COMPLETED"];
const TONES={TENTATIVE:GOLD,CONFIRMED:GREEN,CANCELLED:RED,COMPLETED:MUT};
const EMPTY={eventDate:"",eventTitle:"",expectedGuests:"",hostName:"",residentIdentifier:"",status:"TENTATIVE",notes:""};
const unwrap=v=>v?.data??v??{};
const getItems=r=>{const d=unwrap(r);return d.items??d.bookings??d.rows??(Array.isArray(d)?d:[])};
const getTotal=(r,n)=>{const d=unwrap(r);return Number(d.total??d.totalItems??d.pagination?.total??n)};
const pretty=d=>d?new Date(`${d}T00:00:00`).toLocaleDateString("en-IN",{weekday:"short",day:"2-digit",month:"short"}):"—";
const distance=d=>d?Math.round((new Date(`${d}T00:00:00`).getTime()-new Date(new Date().toISOString().slice(0,10)+"T00:00:00").getTime())/86400000):99;
const money=n=>`₹${Number(n||0).toLocaleString("en-IN")}`, time=v=>v?String(v).slice(0,5):"";
const msg=e=>e?.message||"Something went wrong";

export default function BanquetTab(){
  const {projectId,user}=useAuth();
  const [searchParams]=useSearchParams();
  const selectedProjectId=searchParams.get("projectId");
  const managerProjectId=user?.roleProfiles?.find(profile=>profile?.projectId)?.projectId||projectId;
  const pid=user?.role==="MANAGER"
    ? managerProjectId
    : selectedProjectId&&selectedProjectId!=="all"?selectedProjectId:undefined;
  const [timeline,setTimeline]=useState("UPCOMING");
  const [page,setPage]=useState(1),limit=20,[rows,setRows]=useState([]),[total,setTotal]=useState(0),[summary,setSummary]=useState({});
  const [loading,setLoading]=useState(false),[saving,setSaving]=useState(false),[exporting,setExporting]=useState(false),[formOpen,setFormOpen]=useState(false),[form,setForm]=useState(EMPTY);
  const [residentQuery,setResidentQuery]=useState(""),[residentOptions,setResidentOptions]=useState([]),[selectedResident,setSelectedResident]=useState(null),[residentsLoading,setResidentsLoading]=useState(false);
  const load=useCallback(async()=>{if(!pid)return;setLoading(true);try{const today=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Kolkata",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date()),[list,allBookings,overviewResponse]=await Promise.all([getBanquetBookingsApi({projectId:pid,timeline,page,limit}),getBanquetBookingsApi({projectId:pid,timeline:"ALL",page:1,limit:100}),getManagerDashboardOverviewApi({projectId:pid,date:today})]);const items=getItems(list),all=getItems(allBookings),overview=unwrap(overviewResponse),nextBanquet=overview.cards?.nextBanquet||{};setRows(items);setTotal(getTotal(list,items.length));setSummary({upcomingEvents:nextBanquet.upcomingEvents??0,nextEvent:nextBanquet.nextEvent||null,guestsBooked:all.filter(b=>(b.eventDate||"")>=today&&["TENTATIVE","CONFIRMED"].includes(b.status)).reduce((sum,b)=>sum+Number(b.expectedGuests||0),0),pastEvents:all.filter(b=>(b.eventDate||"")<today||b.status==="COMPLETED").length})}catch(e){toast.error(msg(e))}finally{setLoading(false)}},[pid,timeline,page]);
  useEffect(()=>{load()},[load]); useEffect(()=>setPage(1),[timeline]);
  useEffect(()=>{if(!formOpen)return;const timer=setTimeout(async()=>{setResidentsLoading(true);try{const [searchResponse,cardResponse]=await Promise.all([getUsersApi({limit:20,role:"RESIDENT",search:residentQuery||undefined}),residentQuery&&!residentQuery.includes(" ")?getUsersApi({limit:10,role:"RESIDENT",cardNumber:residentQuery.toUpperCase()}):Promise.resolve(null)]);const list=response=>{const data=unwrap(response);return data.users??data.items??(Array.isArray(data)?data:[])};const merged=[...list(searchResponse),...list(cardResponse)].filter((resident,index,all)=>all.findIndex(item=>item.id===resident.id)===index);setResidentOptions(merged)}catch(e){toast.error(msg(e))}finally{setResidentsLoading(false)}},350);return()=>clearTimeout(timer)},[residentQuery,formOpen]);
  const create=()=>{setForm(EMPTY);setResidentQuery("");setSelectedResident(null);setFormOpen(true)};
  const save=async()=>{if(!form.eventDate||!form.eventTitle.trim()||!form.hostName.trim()||Number(form.expectedGuests)<1)return toast.error("Date, event, host and expected guests are required");if(!form.residentIdentifier)return toast.error("Select a resident card");setSaving(true);const p={...form,expectedGuests:Number(form.expectedGuests)};try{await createBanquetBookingApi({...p,projectId:pid});toast.success("Booking created");setFormOpen(false);await load()}catch(e){toast.error(msg(e))}finally{setSaving(false)}};
  const status=async(b,s)=>{const verb=s==="CANCELLED"?"cancel":s==="COMPLETED"?"complete":"confirm";if(!confirm(`Are you sure you want to ${verb} “${b.eventTitle||b.title}”?`))return;try{s==="CANCELLED"?await cancelBanquetBookingApi(b.id,"Cancelled by manager"):await updateBanquetStatusApi(b.id,{status:s});toast.success(`Booking ${s.toLowerCase()}`);await load()}catch(e){toast.error(msg(e))}};
  const exportFile=async()=>{if(!pid)return;setExporting(true);try{const blob=await exportBanquetBookingsApi({projectId:pid}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`banquet-bookings-${new Date().toISOString().slice(0,10)}.xlsx`;a.click();URL.revokeObjectURL(url)}catch(e){toast.error(msg(e))}finally{setExporting(false)}};
  const n=summary.nextEvent,nextDate=typeof n==="object"?(n.eventDate||n.date):n,nextTitle=typeof n==="object"?(n.eventTitle||n.title):"Next scheduled event";
  const cards=[[<CalendarTodayOutlined/>,"UPCOMING EVENTS",summary.upcomingEvents??0,"confirmed + tentative"],[<ScheduleOutlined/>,"NEXT EVENT",nextDate?(distance(nextDate)===0?"Today":pretty(nextDate)):"—",nextDate?nextTitle:"diary clear"],[<PeopleOutlined/>,"GUESTS BOOKED",summary.guestsBooked??0,"across upcoming"],[<DoneAll/>,"PAST EVENTS",summary.pastEvents??0,"completed or elapsed"]];
  return <Box sx={{display:"flex",flexDirection:"column",gap:2.5}}>
    <Box sx={{display:"flex",alignItems:"center",flexWrap:"wrap",gap:2}}><Box><Typography sx={{fontFamily:'"Cormorant Garamond",serif',fontSize:"1.7rem",fontWeight:600,color:INK}}>Banquet</Typography><Typography sx={{fontSize:".85rem",color:MUT}}>Day-wise hall diary, guest counts & confirmations</Typography></Box><Box sx={{ml:"auto",display:"flex",gap:1}}><Button onClick={create} disabled={!pid} variant="contained" startIcon={<Add/>} sx={{bgcolor:BRAND,textTransform:"none",boxShadow:"none"}}>Add booking</Button><Button onClick={exportFile} disabled={exporting||!pid} startIcon={exporting?<CircularProgress size={16}/>:<Download/>} sx={{bgcolor:BG,color:BRAND,textTransform:"none"}}>Export Excel</Button></Box></Box>
    {!pid&&<Paper elevation={0} sx={{p:2,color:RED,border:`1px solid ${RED}44`}}>{user?.role==="MANAGER"?"No project is assigned to this manager.":"Select a project from the project dropdown before managing banquet bookings."}</Paper>}
    <Box sx={{display:"grid",gridTemplateColumns:{xs:"1fr 1fr",lg:"repeat(4,1fr)"},gap:1.5}}>{cards.map(([icon,label,value,sub])=><Paper key={label} elevation={0} sx={{p:2,border:`1px solid ${LINE}`,borderRadius:"12px"}}><Box sx={{display:"flex",gap:.8,alignItems:"center",color:BRAND,mb:1}}>{icon}<Typography sx={{fontSize:".62rem",fontWeight:700,color:MUT,letterSpacing:".5px"}}>{label}</Typography></Box><Typography sx={{fontFamily:'"Cormorant Garamond",serif',fontSize:"1.55rem",fontWeight:600,color:INK}}>{loading?"—":value}</Typography><Typography sx={{fontSize:".72rem",color:MUT}}>{sub}</Typography></Paper>)}</Box>
    {formOpen&&<BookingForm form={form} setForm={setForm} saving={saving} save={save} close={()=>setFormOpen(false)} residentOptions={residentOptions} selectedResident={selectedResident} setSelectedResident={setSelectedResident} residentQuery={residentQuery} setResidentQuery={setResidentQuery} residentsLoading={residentsLoading}/>}
    <Box sx={{display:"flex",gap:1}}>{["UPCOMING","PAST","ALL"].map(x=><Button key={x} onClick={()=>setTimeline(x)} sx={{textTransform:"none",borderRadius:"20px",px:2.5,bgcolor:timeline===x?BRAND:BG,color:timeline===x?"#fff":MUT}}>{x[0]+x.slice(1).toLowerCase()}</Button>)}</Box>
    <Stack spacing={1.5}>{loading&&<Box sx={{py:5,textAlign:"center"}}><CircularProgress size={28}/></Box>}{!loading&&!rows.length&&<Paper elevation={0} sx={{py:5,textAlign:"center",border:`1px solid ${LINE}`,borderRadius:"14px",color:MUT}}>No banquet bookings found.</Paper>}{!loading&&rows.map(b=><BookingRow key={b.id} booking={b} changeStatus={status}/>)}</Stack>
    {Math.ceil(total/limit)>1&&<Pagination count={Math.ceil(total/limit)} page={page} onChange={(_,v)=>setPage(v)} color="primary" sx={{alignSelf:"center"}}/>}
  </Box>
}

function Choice({label,value,values,onChange,allowAll=true}){return <FormControl size="small"><InputLabel>{label}</InputLabel><Select label={label} value={value} onChange={e=>onChange(e.target.value)}>{allowAll&&<MenuItem value="">All</MenuItem>}{values.map(x=><MenuItem key={x} value={x}>{x.replaceAll("_"," ")}</MenuItem>)}</Select></FormControl>}
function BookingForm({form,setForm,saving,save,close,residentOptions,selectedResident,setSelectedResident,residentQuery,setResidentQuery,residentsLoading}){const set=(k,v)=>setForm({...form,[k]:v});return <Paper elevation={0} sx={{p:2.5,border:`1px solid ${LINE}`,borderRadius:"14px"}}><Typography sx={{fontWeight:700,color:INK,mb:2}}>New booking</Typography><Box sx={{display:"grid",gridTemplateColumns:{xs:"1fr",sm:"repeat(3,1fr)"},gap:2}}><TextField label="Event date" type="date" size="small" value={form.eventDate} onChange={e=>set("eventDate",e.target.value)} InputLabelProps={{shrink:true}}/><TextField label="Event title" size="small" value={form.eventTitle} onChange={e=>set("eventTitle",e.target.value)}/><TextField label="Expected guests" type="number" size="small" value={form.expectedGuests} onChange={e=>set("expectedGuests",e.target.value)}/><Autocomplete sx={{gridColumn:{sm:"span 2"}}} options={residentOptions} filterOptions={x=>x} value={selectedResident} inputValue={residentQuery} loading={residentsLoading} isOptionEqualToValue={(a,b)=>a.id===b.id} getOptionLabel={r=>`${r.name||"Unknown"}${r.cardNumber?` · ${r.cardNumber}`:""}${r.phone?` · ${r.phone}`:""}`} onInputChange={(_,v)=>setResidentQuery(v)} onChange={(_,r)=>{setSelectedResident(r);setForm({...form,residentIdentifier:r?.cardNumber||"",hostName:r?.name||form.hostName})}} renderInput={params=><TextField {...params} label="Search resident card" size="small" required InputProps={{...params.InputProps,endAdornment:<>{residentsLoading&&<CircularProgress size={16}/>} {params.InputProps.endAdornment}</>}}/>}/><TextField label="Host name" size="small" value={form.hostName} onChange={e=>set("hostName",e.target.value)}/><Choice label="Booking status" value={form.status} values={STATUSES} onChange={v=>set("status",v)} allowAll={false}/><TextField label="Notes" size="small" multiline value={form.notes} onChange={e=>set("notes",e.target.value)} sx={{gridColumn:{sm:"span 2"}}}/><Box sx={{gridColumn:{sm:"span 3"},display:"flex",gap:1,alignItems:"center",flexWrap:"wrap"}}><Button onClick={save} disabled={saving} variant="contained" sx={{bgcolor:GREEN,textTransform:"none"}}>{saving?"Saving…":"Save booking"}</Button><Button onClick={close} disabled={saving} sx={{color:MUT,textTransform:"none"}}>Close</Button><Typography sx={{fontSize:".72rem",color:MUT}}>Search by resident name or card ID and select the resident.</Typography></Box></Box></Paper>}
function BookingRow({booking:b,changeStatus}){const s=b.status||"TENTATIVE",tone=TONES[s]||MUT,date=b.eventDate||b.date,d=distance(date),times=[time(b.startTime),time(b.endTime)].filter(Boolean).join("–"),actionSx={textTransform:"none",fontSize:".72rem",fontWeight:600,py:.55,px:1.6,borderRadius:"8px",minWidth:0,boxShadow:"none"};return <Paper elevation={0} sx={{p:2,border:`1px solid ${d>=0&&d<=1?"#bca47c88":LINE}`,borderRadius:"14px"}}><Box sx={{display:"flex",gap:2,alignItems:"flex-start",flexWrap:"wrap"}}><Box sx={{width:48,height:48,borderRadius:"12px",bgcolor:`${tone}14`,display:"grid",placeItems:"center",color:tone,fontWeight:700}}>{date?.slice(8,10)||"—"}</Box><Box sx={{flex:1,minWidth:220}}><Typography sx={{fontWeight:700,color:INK}}>{b.eventTitle||b.title||"Untitled event"} · {b.expectedGuests??b.guestCount??0} guests</Typography><Typography sx={{fontSize:".75rem",color:MUT,mt:.4}}>{b.bookingCode||b.bookingNumber||b.code||b.id} · {pretty(date)}{times?` · ${times}`:""}</Typography><Typography sx={{fontSize:".75rem",color:MUT,mt:.2}}>Host {b.hostName||b.hostUser?.name||b.host?.name||"—"}{b.flat?.number||b.flatNumber?` · ${b.flat?.number||b.flatNumber}`:""} · deposit {money(b.securityDepositAmount??b.depositAmount)} ({(b.depositStatus||"NOT_REQUIRED").replaceAll("_"," ")})</Typography>{b.notes&&<Typography sx={{fontSize:".8rem",color:INK,mt:1}}>{b.notes}</Typography>}</Box><Box sx={{display:"flex",flexDirection:"column",alignItems:"flex-end",gap:1}}><Box sx={{px:1.2,py:.25,borderRadius:"5px",bgcolor:`${tone}14`,color:tone,fontSize:".67rem",fontWeight:700}}>{s}</Box>{d===0&&<Typography sx={{fontSize:".65rem",fontWeight:700,color:GOLD}}>TODAY</Typography>}<Box sx={{display:"flex",gap:1,flexWrap:"wrap",justifyContent:"flex-end"}}>{!["CANCELLED","COMPLETED"].includes(s)&&<><Button onClick={()=>changeStatus(b,"CANCELLED")} sx={{...actionSx,bgcolor:"#fbe9e5",color:RED,"&:hover":{bgcolor:"#f8d7da"}}}>Cancel</Button><Button onClick={()=>changeStatus(b,"COMPLETED")} sx={{...actionSx,bgcolor:"#dbeafe",color:BRAND,"&:hover":{bgcolor:"#cfe1fa"}}}>Complete</Button></>}</Box></Box></Box></Paper>}
