// @ts-nocheck
import { useCallback, useEffect, useMemo, useState } from "react";
import { Box, Button, CircularProgress, FormControl, MenuItem, Pagination, Paper, Select, Stack, TextField, Typography } from "@mui/material";
import { Add, Attachment, Download, Inventory2Outlined, Link as LinkIcon, Upload } from "@mui/icons-material";
import { useSearchParams } from "react-router-dom";
import { toast } from "react-hot-toast";
import { useAuth } from "@/contexts/AuthContext";
import { uploadDocumentApi } from "@/apis/document";
import { createManagerRequestApi, exportManagerRequestsApi, getManagerRequestsApi, getManagerRequestsSummaryApi, updateManagerRequestApi, updateManagerRequestStatusApi } from "@/apis/managerRequests";

const BRAND="#24528C",GREEN="#22c55e",GOLD="#a17a3f",MUT="#64748b",INK="#1e293b",BG="#f1f5f9",LINE="#e2e8f0",RED="#ef4444";
const STATUSES=["OPEN","WITH_CRM","WITH_PURCHASE","APPROVED","REJECTED","FULFILLED","CANCELLED"],URGENCIES=["LOW","NORMAL","HIGH","URGENT"],DEPARTMENTS=["CRM","PURCHASE","MANAGER"];
const EMPTY={title:"",quantity:"1",urgency:"NORMAL",targetDepartment:"PURCHASE",referenceLink:"",note:"",attachmentUrls:[],adminNotes:""};
const TONES={OPEN:[GOLD,"#faf7f2"],WITH_CRM:[GOLD,"#faf7f2"],WITH_PURCHASE:[BRAND,"#eef2ff"],APPROVED:[GREEN,"#ecfdf5"],REJECTED:[RED,"#fef2f2"],FULFILLED:[GREEN,"#ecfdf5"],CANCELLED:[MUT,BG]};
const unwrap=value=>value?.data??value??{};
const itemsFrom=response=>{const data=unwrap(response);return data.items??data.requests??data.rows??(Array.isArray(data)?data:[])};
const totalFrom=(response,fallback)=>{const data=unwrap(response);return Number(data.total??data.totalItems??data.pagination?.total??fallback)};
const pretty=value=>String(value||"").replaceAll("_"," ").toLowerCase().replace(/\b\w/g,char=>char.toUpperCase());
const displayDate=value=>value?new Date(value).toLocaleDateString("en-IN",{day:"2-digit",month:"short"}):"—";
const monthRange=()=>{const now=new Date(),format=date=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;return{dateFrom:format(new Date(now.getFullYear(),now.getMonth(),1)),dateTo:format(new Date(now.getFullYear(),now.getMonth()+1,0))}};

export default function RequestsTab(){
  const {user,projectId}=useAuth();
  const [searchParams]=useSearchParams(),selectedProjectId=searchParams.get("projectId"),managerProjectId=user?.roleProfiles?.find(profile=>profile?.projectId)?.projectId||projectId;
  const pid=user?.role==="MANAGER"?managerProjectId:selectedProjectId&&selectedProjectId!=="all"?selectedProjectId:undefined;
  const dates=useMemo(monthRange,[]),[rows,setRows]=useState([]),[summary,setSummary]=useState({}),[total,setTotal]=useState(0),[page,setPage]=useState(1),limit=20;
  const [statusFilter,setStatusFilter]=useState("ALL"),[urgencyFilter,setUrgencyFilter]=useState("ALL"),[search,setSearch]=useState(""),[loading,setLoading]=useState(false),[exporting,setExporting]=useState(false);
  const [formOpen,setFormOpen]=useState(false),[editing,setEditing]=useState(null),[form,setForm]=useState(EMPTY),[saving,setSaving]=useState(false),[uploading,setUploading]=useState(false);
  const load=useCallback(async()=>{if(!pid)return;setLoading(true);try{const params={projectId:pid,...(statusFilter!=="ALL"?{status:statusFilter}:{}),...(urgencyFilter!=="ALL"?{urgency:urgencyFilter}:{}),...(search.trim()?{search:search.trim()}:{}),page,limit},[list,sum]=await Promise.all([getManagerRequestsApi(params),getManagerRequestsSummaryApi({projectId:pid,...dates})]),items=itemsFrom(list);setRows(items);setTotal(totalFrom(list,items.length));setSummary(unwrap(sum))}catch(error){toast.error(error?.message||"Failed to load requests")}finally{setLoading(false)}},[pid,statusFilter,urgencyFilter,search,page,dates]);
  useEffect(()=>{const timer=setTimeout(load,300);return()=>clearTimeout(timer)},[load]);useEffect(()=>setPage(1),[statusFilter,urgencyFilter,search]);
  const startCreate=()=>{setEditing(null);setForm(EMPTY);setFormOpen(true)};
  const startEdit=request=>{setEditing(request);setForm({title:request.title||"",quantity:String(request.quantity||1),urgency:request.urgency||"NORMAL",targetDepartment:request.targetDepartment||"PURCHASE",referenceLink:request.referenceLink||"",note:request.note||"",attachmentUrls:request.attachmentUrls||[],adminNotes:request.adminNotes||""});setFormOpen(true)};
  const attach=async event=>{const files=Array.from(event.target.files||[]);if(!files.length)return;setUploading(true);try{const urls=await Promise.all(files.map(uploadDocumentApi));setForm(current=>({...current,attachmentUrls:[...current.attachmentUrls,...urls]}));toast.success(`${urls.length} attachment${urls.length>1?"s":""} uploaded`)}catch(error){toast.error(error?.message||"Upload failed")}finally{setUploading(false);event.target.value=""}};
  const save=async()=>{if(!form.title.trim()||Number(form.quantity)<1)return toast.error("Title and quantity are required");setSaving(true);const payload={...form,title:form.title.trim(),quantity:Number(form.quantity),referenceLink:form.referenceLink.trim()||undefined,note:form.note.trim()||undefined,adminNotes:form.adminNotes.trim()||undefined};try{editing?await updateManagerRequestApi(editing.id,payload):await createManagerRequestApi({...payload,projectId:pid});toast.success(editing?"Request updated":"Request sent");setFormOpen(false);await load()}catch(error){toast.error(error?.message||"Failed to save request")}finally{setSaving(false)}};
  const moveStatus=async(request,newStatus)=>{try{await updateManagerRequestStatusApi(request.id,{status:newStatus});toast.success("Request status updated");await load()}catch(error){toast.error(error?.message||"Failed to update status")}};
  const exportExcel=async()=>{if(!pid)return;setExporting(true);try{const blob=await exportManagerRequestsApi({projectId:pid,...(statusFilter!=="ALL"?{status:statusFilter}:{}),...(urgencyFilter!=="ALL"?{urgency:urgencyFilter}:{}),...(search.trim()?{search:search.trim()}: {})}),url=URL.createObjectURL(blob),anchor=document.createElement("a");anchor.href=url;anchor.download=`manager-requests-${new Date().toISOString().slice(0,10)}.xlsx`;anchor.click();URL.revokeObjectURL(url)}catch(error){toast.error(error?.message||"Export failed")}finally{setExporting(false)}};
  return <Box sx={{display:"flex",flexDirection:"column",gap:2.5}}>
    <Box sx={{display:"flex",alignItems:"center",gap:2,flexWrap:"wrap"}}><Box><Typography sx={{fontFamily:'"Cormorant Garamond",serif',fontSize:"1.7rem",fontWeight:600,color:INK}}>Requests</Typography><Typography sx={{fontSize:".85rem",color:MUT}}>Raise a purchase request to CRM & Purchase</Typography></Box><Box sx={{ml:"auto",display:"flex",gap:1.5}}><Button onClick={startCreate} disabled={!pid} variant="contained" startIcon={<Add/>} sx={{bgcolor:BRAND,textTransform:"none",boxShadow:"none"}}>New request</Button><Button onClick={exportExcel} disabled={exporting||!pid} startIcon={exporting?<CircularProgress size={16}/>:<Download/>} sx={{bgcolor:BG,color:BRAND,textTransform:"none"}}>Export Excel</Button></Box></Box>
    {!pid&&<Paper elevation={0} sx={{p:2,color:RED,border:`1px solid ${RED}44`}}>{user?.role==="MANAGER"?"No project is assigned to this manager.":"Select a project before managing requests."}</Paper>}
    {formOpen&&<RequestForm form={form} setForm={setForm} editing={editing} saving={saving} uploading={uploading} attach={attach} save={save} close={()=>setFormOpen(false)}/>}
    {loading?<Box sx={{py:6,textAlign:"center"}}><CircularProgress/></Box>:rows.length===0?<Paper elevation={0} sx={{py:6,textAlign:"center",border:`1px solid ${LINE}`,borderRadius:"16px",color:MUT}}>No requests found.</Paper>:<Stack spacing={1.5}>{rows.map(request=><RequestRow key={request.id} request={request}/>)}</Stack>}
    {Math.ceil(total/limit)>1&&<Pagination count={Math.ceil(total/limit)} page={page} onChange={(_,value)=>setPage(value)} color="primary" sx={{alignSelf:"center"}}/>}
  </Box>;
}

function RequestForm({form,setForm,editing,saving,uploading,attach,save,close}){const set=(key,value)=>setForm({...form,[key]:value}),fieldSx={"& .MuiOutlinedInput-root":{borderRadius:"10px",fontSize:".85rem"}};return <Paper elevation={0} sx={{p:3,borderRadius:"16px",border:`1px solid ${LINE}`}}><Box sx={{display:"grid",gridTemplateColumns:{xs:"1fr",sm:"2fr 1fr"},gap:2.5}}><TextField label="What do you need" placeholder="e.g. Pool cleaning gear — telescopic vacuum set" size="small" value={form.title} onChange={event=>set("title",event.target.value)} sx={fieldSx}/><TextField label="Quantity" type="number" size="small" value={form.quantity} onChange={event=>set("quantity",event.target.value)} sx={fieldSx}/><FormControl size="small"><Select value={form.urgency} onChange={event=>set("urgency",event.target.value)} sx={{borderRadius:"10px"}}>{URGENCIES.map(value=><MenuItem key={value} value={value}>{pretty(value)}</MenuItem>)}</Select></FormControl><TextField label="Reference link (looks like this)" placeholder="https://..." size="small" value={form.referenceLink} onChange={event=>set("referenceLink",event.target.value)} sx={fieldSx}/><TextField label="Note for CRM / Purchase" placeholder="Why it's needed, spec, deadline" size="small" value={form.note} onChange={event=>set("note",event.target.value)} sx={{...fieldSx,gridColumn:{sm:"span 2"}}}/></Box><Box sx={{display:"flex",alignItems:"center",gap:1.5,mt:2,flexWrap:"wrap"}}><Button component="label" disabled={uploading} startIcon={uploading?<CircularProgress size={16}/>:<Upload/>} sx={{bgcolor:BG,color:BRAND,textTransform:"none",fontWeight:600,borderRadius:"10px",px:2.5}}>Attach photo / video {form.attachmentUrls.length>0?`(${form.attachmentUrls.length})`:""}<input hidden multiple type="file" accept="image/*,video/*" onChange={attach}/></Button><Box sx={{ml:"auto",display:"flex",gap:1}}><Button onClick={save} disabled={saving||uploading} variant="contained" sx={{bgcolor:GREEN,textTransform:"none",fontWeight:600,borderRadius:"10px",px:3,boxShadow:"none"}}>{saving?"Saving…":editing?"Update request":"Send request"}</Button><Button onClick={close} sx={{bgcolor:BG,color:MUT,textTransform:"none",fontWeight:600,borderRadius:"10px",px:3}}>Cancel</Button></Box></Box><Typography sx={{fontSize:".65rem",color:MUT,mt:1.5}}>Attach photos or videos to support the request.</Typography></Paper>}

function RequestRow({request}){const status=request.status||"OPEN",[tone,bg]=TONES[status]||TONES.OPEN,attachments=request.attachmentUrls||[],createdBy=request.createdByUser?.name||request.creator?.name||request.createdByName||"Manager";return <Paper elevation={0} sx={{p:2.5,borderRadius:"16px",border:`1px solid ${LINE}`}}><Box sx={{display:"flex",gap:2}}><Box sx={{width:42,height:42,borderRadius:"12px",display:"grid",placeItems:"center",bgcolor:bg,color:tone,flexShrink:0}}><Inventory2Outlined/></Box><Box sx={{flex:1,minWidth:0}}><Box sx={{display:"flex",justifyContent:"space-between",gap:2}}><Typography sx={{fontSize:".95rem",fontWeight:700,color:INK}}>{request.title}</Typography><Box sx={{px:1.5,py:.3,borderRadius:"12px",bgcolor:bg,color:tone,fontSize:".67rem",fontWeight:700,whiteSpace:"nowrap"}}>{pretty(status)}</Box></Box><Typography sx={{fontSize:".75rem",color:MUT,mt:.4}}>{request.requestCode||request.code||request.id} · qty {request.quantity||1} · {pretty(request.urgency||"NORMAL")} · raised by {createdBy} · {displayDate(request.createdAt)}</Typography>{request.note&&<Typography sx={{fontSize:".82rem",color:INK,mt:1}}>{request.note}</Typography>}<Box sx={{display:"flex",gap:2,alignItems:"center",mt:1,flexWrap:"wrap"}}>{request.referenceLink&&<Typography component="a" href={request.referenceLink} target="_blank" rel="noreferrer" sx={{display:"flex",alignItems:"center",gap:.5,fontSize:".75rem",color:BRAND,textDecoration:"none"}}><LinkIcon sx={{fontSize:14}}/>{request.referenceLink}</Typography>}{attachments.length>0&&<Typography sx={{display:"flex",alignItems:"center",gap:.5,fontSize:".75rem",color:MUT}}><Attachment sx={{fontSize:14}}/>{attachments.length} attachment{attachments.length>1?"s":""}</Typography>}</Box></Box></Box></Paper>}
